on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: 'us-east-1'
      tf-version:
        required: false
        type: string
        default: '1.14.8'
      apply:
        required: false
        type: boolean
        default: false
    secrets:
      AWS_GITHUB_ROLE_ARN:
        required: true

env:
  AWS_DEFAULT_REGION: ${{ inputs.aws-region || 'us-east-1' }}
  TF_VERSION: ${{ inputs.tf-version || '1.14.8' }}
  TF_IN_AUTOMATION: true
  # Set TF Debug level accordingly: ERROR, WARN, INFO,DEBUG, TRACE or null ('')
  #  to turn it off, oe comment the line below.
  TF_LOG: ''

jobs:
  run-change:
    name: Run Change
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Check changed files
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            lambda:
              - 'src/create_short_url/**'
              - 'src/redirect/**'
              - 'src/shared/**'
              - 'Dockerfile'
            terraform:
              - 'terraform/**'
              - 'src/frontend/**'

      - name: Setup Python
        if: steps.changes.outputs.lambda == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: steps.changes.outputs.lambda == 'true'
        run: make install-dev

      - name: Run Tests
        if: steps.changes.outputs.lambda == 'true'
        run: make test

      - name: Configure AWS Credentials
        if: steps.changes.outputs.terraform == 'true' || steps.changes.outputs.lambda == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set up Terraform
        if: steps.changes.outputs.terraform == 'true'
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ inputs.tf-version }}

      - name: TF Init and Validate
        if: steps.changes.outputs.terraform == 'true'
        run: |
          make init
          make validate

      - name: TF Plan
        if: ${{ !inputs.apply && steps.changes.outputs.terraform == 'true' }}
        run: make plan
        timeout-minutes: 2

      - name: TF Apply
        if: ${{ inputs.apply && steps.changes.outputs.terraform == 'true' }}
        run: make apply
        timeout-minutes: 5

      - name: Validate Docker build
        if: ${{ !inputs.apply && steps.changes.outputs.lambda == 'true' }}
        run: make build-only

      - name: Build images
        if: ${{ inputs.apply && steps.changes.outputs.lambda == 'true' }}
        run: make build

      - name: Push images
        if: ${{ inputs.apply && steps.changes.outputs.lambda == 'true' }}
        run: make push
